// Generated by CoffeeScript 1.10.0
(function() {
  var config, express, router;

  express = require('express');

  router = express.Router();

  config = require('../config/config');

  router.get('/', function(req, res, next) {
    return res.render('index', {
      title: config.title,
      description: config.description,
      host: config.host,
      scheme: config.scheme
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
