// Generated by CoffeeScript 1.10.0
(function() {
  var _;

  _ = require('lodash');

  module.exports = function(app, resources, spec, config) {
    var definitions, paths, specification;
    if (spec == null) {
      spec = '/spec';
    }
    paths = {};
    definitions = {};
    _.each(resources, function(resource) {
      var key, newKey, newPaths, ref, swagger, value;
      swagger = resource.swagger();
      if ((swagger.paths["/carts"] != null)) {
        swagger.paths["/carts"].get.parameters.push({
          name: 'query',
          "in": 'query',
          description: 'Query by example. Pass a JSON object to find, for example: {"Id": "someid"}.',
          type: 'string',
          required: false,
          "default": ''
        });
      }
      newPaths = [];
      ref = swagger.paths;
      for (key in ref) {
        value = ref[key];
        newKey = key.replace('CartsId', 'Id');
        newPaths[newKey] = value;
      }
      paths = _.assign(paths, newPaths);
      return definitions = _.assign(definitions, swagger.definitions);
    });
    specification = {
      swagger: '2.0',
      info: {
        description: config.description,
        version: config.version,
        title: config.title,
        contact: {
          name: config.author
        }
      },
      host: config.host,
      basePath: config.basepath,
      schemes: [config.scheme],
      definitions: definitions,
      paths: paths
    };
    return app.get(spec, function(req, res, next) {
      return res.json(specification);
    });
  };

}).call(this);

//# sourceMappingURL=swagger.js.map
