// Generated by CoffeeScript 1.10.0
(function() {
  var CartSchema, ItemSchema, Mongoose, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ItemSchema = new Schema({
    price: {
      type: Number,
      index: false
    },
    quantity: {
      type: Number,
      index: false
    },
    sku: {
      type: String,
      index: true
    }
  }, {
    strict: false
  });

  CartSchema = new Schema({
    items: [ItemSchema],
    total: {
      type: Number,
      index: false
    }
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Cart", CartSchema),
    schema: CartSchema
  };

}).call(this);

//# sourceMappingURL=cart.js.map
