// Generated by CoffeeScript 1.10.0
(function() {
  var ItemModel, ItemSchema, Mongoose, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ItemSchema = new Schema({
    sku: String,
    price: String,
    quantity: Number
  });

  ItemModel = Mongoose.model("Item", ItemSchema);

  module.exports = {
    model: ItemModel,
    schema: ItemSchema
  };

}).call(this);

//# sourceMappingURL=Item.js.map
